In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\admin\Desktop\Ecommerce Project\ecommerce.csv")
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Cost_Price
0,1,2022/01/25,9208,Aarav Verma,West,Pune,Electronics,Laptop,Laptop - Model 328,5,77155,13,Debit Card,320,49717.23
1,2,2022/07/23,7944,Ananya Verma,South,Kochi,Beauty,Skincare,Skincare - Model 481,5,1198,21,UPI,404,966.76
2,3,2022/07/25,6429,Rohan Gupta,West,Pune,Home,Furniture,Furniture - Model 942,5,4141,4,Debit Card,416,3441.00
3,4,2023/08/07,9765,Vivaan Kapoor,South,Hyderabad,Clothing,Jeans,Jeans - Model 349,5,4818,23,Debit Card,355,3898.49
4,5,2023/04/09,7883,Aditya Nair,South,Hyderabad,Clothing,Kurti,Kurti - Model 433,5,1549,4,Credit Card,463,1385.98

In [6]:
#Inspect the structure of the dataset

df.shape #rows and columns in the dataset
df.columns #column names of dataframes
df.info() #summary of dataset structure
df.describe() #statistical summary for numerical columns - mean, count, avg, etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1200 non-null   int64
 1   Order_Date     1200 non-null   object
 2   Customer_ID    1200 non-null   int64
 3   Customer_Name  1200 non-null   object
 4   Region         1200 non-null   object
 5   City           1200 non-null   object
 6   Category       1200 non-null   object
 7   Sub_Category   1200 non-null   object
 8   Product_Name   1200 non-null   object
 9   Quantity       1200 non-null   int64
 10  Price          1200 non-null   int64
 11  Discount       1200 non-null   int64
 12  Payment_Mode   1200 non-null   object
 13  Shipping_Cost  1200 non-null   int64
 14  Cost_Price     1200 non-null   float64
dtypes: float64(1), int64(6), object(8)
memory usage: 140.8+ KB

,Order_ID,Customer_ID,Quantity,Price,Discount,Shipping_Cost,Cost_Price
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,600.500000,5541.620000,2.963333,13756.997500,14.719167,271.234167,9697.271717
std,346.554469,2622.284857,1.393535,17872.198397,8.912809,132.051141,12935.149031
min,1.000000,1008.000000,1.000000,325.000000,0.000000,50.000000,172.100000
25%,300.750000,3268.500000,2.000000,2766.500000,7.000000,155.000000,1900.577500
50%,600.500000,5609.000000,3.000000,5624.500000,15.000000,271.500000,3860.680000
75%,900.250000,7813.000000,4.000000,17025.500000,22.000000,383.000000,12046.847500
max,1200.000000,9998.000000,5.000000,78681.000000,30.000000,500.000000,67122.860000

In [7]:
df.isnull().sum() #checking for any null values

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Region           0
City             0
Category         0
Sub_Category     0
Product_Name     0
Quantity         0
Price            0
Discount         0
Payment_Mode     0
Shipping_Cost    0
Cost_Price       0
dtype: int64

In [10]:
df.duplicated().sum() #check for any duplicate rows
df.drop_duplicates(inplace=True) #drop duplicate rows if any

In [12]:
df['Order_Date'] = pd.to_datetime(df['Order_Date']) #Change the type of order_date to date instead of object
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1200 non-null   int64
 1   Order_Date     1200 non-null   datetime64[ns]
 2   Customer_ID    1200 non-null   int64
 3   Customer_Name  1200 non-null   object
 4   Region         1200 non-null   object
 5   City           1200 non-null   object
 6   Category       1200 non-null   object
 7   Sub_Category   1200 non-null   object
 8   Product_Name   1200 non-null   object
 9   Quantity       1200 non-null   int64
 10  Price          1200 non-null   int64
 11  Discount       1200 non-null   int64
 12  Payment_Mode   1200 non-null   object
 13  Shipping_Cost  1200 non-null   int64
 14  Cost_Price     1200 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(6), object(7)
memory usage: 140.8+ KB

In [16]:
df['Revenue'] = df['Quantity'] * df['Price'] * (1 - df['Discount']/100) #Quantity x Price x Percentage of the price paid
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Sub_Category,Product_Name,Quantity,Price,Discount,Payment_Mode,Shipping_Cost,Cost_Price,Revenue
0,1,2022-01-25,9208,Aarav Verma,West,Pune,Electronics,Laptop,Laptop - Model 328,5,77155,13,Debit Card,320,49717.23,335624.25
1,2,2022-07-23,7944,Ananya Verma,South,Kochi,Beauty,Skincare,Skincare - Model 481,5,1198,21,UPI,404,966.76,4732.10
2,3,2022-07-25,6429,Rohan Gupta,West,Pune,Home,Furniture,Furniture - Model 942,5,4141,4,Debit Card,416,3441.00,19876.80
3,4,2023-08-07,9765,Vivaan Kapoor,South,Hyderabad,Clothing,Jeans,Jeans - Model 349,5,4818,23,Debit Card,355,3898.49,18549.30
4,5,2023-04-09,7883,Aditya Nair,South,Hyderabad,Clothing,Kurti,Kurti - Model 433,5,1549,4,Credit Card,463,1385.98,7435.20

In [19]:
df['Month'] = df['Order_Date'].dt.month #Create a new column Month by extracting it

In [20]:
df['Revenue'].sum() #Get Total Revenue

np.float64(41358117.519999996)

In [29]:
df.groupby('Product_Name')['Revenue'].sum().sort_values(ascending=False).head(10) #Top 10 products by revenue

Product_Name
Headphones - Model 811    389775.00
Smartwatch - Model 168    381602.85
Laptop - Model 328        335624.25
Laptop - Model 226        301369.20
Smartwatch - Model 801    297864.00
Laptop - Model 716        295531.76
Smartwatch - Model 888    291828.60
Mobile - Model 561        291436.80
Smartwatch - Model 406    281246.35
Laptop - Model 776        275163.60
Name: Revenue, dtype: float64

In [30]:
df.groupby('Region')['Revenue'].sum() #Region wide sales

Region
East      9293690.52
North    10708155.82
South    10335253.53
West     11021017.65
Name: Revenue, dtype: float64

In [31]:
df.groupby('Month')['Revenue'].sum() #Monthly sales trend

Month
1     4395388.75
2     3454142.37
3     3115811.65
4     2890614.79
5     2973381.60
6     3534588.13
7     3737752.69
8     3067096.71
9     3708199.06
10    3965995.36
11    2467664.84
12    4047481.57
Name: Revenue, dtype: float64

In [32]:
df['Customer_ID'].value_counts() #Repeat customers

Customer_ID
3854    3
7005    3
8930    2
3795    2
1215    2
       ..
7604    1
2003    1
3922    1
7015    1
5094    1
Name: count, Length: 1134, dtype: int64

In [33]:
df.groupby('Payment_Mode')['Revenue'].sum() #Payment Method analysis

Payment_Mode
COD            11874437.24
Credit Card     9223792.74
Debit Card     11012289.26
UPI             9247598.28
Name: Revenue, dtype: float64

In [3]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Order_Date'] = df['Order_Date'].dt.strftime('%Y-%m-%d') #Changing the date type to yyyy-mm-dd for proper SQL use

In [5]:
df.to_csv("ecommerce_cleaned.csv", index=False)